= Apache Shiro with JWT as Token Showcase
:toc: macro
:toclevels: 4
:idprefix:
:icons: font

https://github.com/bmarwell/shiro-jwt-showcase/actions/workflows/maven.yaml[image:https://github.com/bmarwell/shiro-jwt-showcase/actions/workflows/maven.yaml/badge.svg[Maven
CI]]
https://opensource.org/licenses/Apache-2.0[image:https://img.shields.io/badge/License-Apache_2.0-blue.svg[License]]
https://renovatebot.com[image:https://img.shields.io/badge/renovate-enabled-brightgreen.svg[Renovate]]
link:https://openliberty.io/[image:https://img.shields.io/badge/AppServer-Open%20Liberty-blue[AppServer]]

This project is a showcase how you can use https://shiro.apache.org[Apache Shiro] with JWTs (pronounced: jots).

The idea here is to use as few shipped dependencies as possible.
All dependencies possible should be provided by an JavaEE application server.

toc::[]

== Tech stack

* https://shiro.apache.com[Apache Shiro]
* MicroProfile JWT
* JAX-RS 2.1
* https://maven.apache.org[Apache Maven]

Additional used tech which is optional / swappable:

* https://openliberty.io[IBM OpenLiberty] (any JavaEE + MP application server should do)
* Jakarta CDI 2.0
* Jakarta JSON-B
* JJWT with custom JSON-B serializer (for issuing only)
* MicroProfile Config 2.0

== Sub-Projects

Execute them using `./mvnw -f <projectdir> liberty:dev`.

issuer::
The issuing server to get a JWT from.
Not part of the tutorial, usually transparent for your application.
+
Starts at port 9081 as a side server.
Curl using `curl -H 'accept: application/json' -H 'content-type: application/json' -v -d '{ "username": "me", "password": "me" }' --url "http://localhost:9081/login?roles=admin,user"`.
Credentials are irrelevant, as long as they are the same.

start::
Tutorial start setup.

finish::
Tutorial finish setup.
