name: Maven CI

on:
  workflow_dispatch: { }
  push: { }
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Check code style
        shell: bash
        run: ./mvnw --show-version --errors --batch-mode --no-transfer-progress spotless:check


      - name: Build application with Maven
        shell: bash
        run: ./mvnw --show-version --errors --batch-mode --no-transfer-progress verify -Pdocs
